aaa_authentication:
  login:
    default: local group tacacs+
    console: local
  policies:
    on_failure_log: true
    on_success_log: true
aaa_authorization:
  exec:
    default: local group tacacs+
  commands:
    privilege:
    - level: '15'
      default: local group tacacs+
aaa_root:
  disabled: true
aaa_server_groups:
- name: TacServer
  type: tacacs+
  servers:
  - server: 180.250.33.126
    vrf: MGMT
  - server: 180.250.33.127
    vrf: MGMT
arp:
  aging:
    timeout_default: 1500
banners:
  login: "#\n                                   @\n                                  @@\n                                  @@@\n                                  @@@@\n
    \                             @   @@@@@                      BANCO SANTANDER\n                             @@@   @@@@@@            Grupo
    SANTANDER CENTRAL HISPANO\n                             @@@@    @@@@@\n                             @@@@@    @@@@@\n                              @@@@@@
    \  @@@@\n                      @@@@@@    @@@@@@  @@@@@@@\n                   @@@@@@@@@@    @@@@@@ @@@@@@@@@@@\n                @@@@@@@@@@@@@@@
    \   @@@@@@@@@@@@@@@@@@@\n               @@@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@@@\n              @@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@@\n
    \               @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n                  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n                      @@@@@@@@@@@@@@@@@@@@@@@@@@\n\n############################################################\n#
    \      WARNING: only authorized access is allowed.        #\n#       AVISO: solo se permite acceso a autorizados.       #\n#       Actions
    are monitored and recorded.                #\n#       Sus acciones son monitoreadas y registradas.       #\n############################################################\nEOF\n"
clock:
  timezone: America/Buenos_Aires
config_end: true
daemon_terminattr:
  cvaddrs:
  - 192.168.0.5:9910
  cvauth:
    method: token
    token_file: /tmp/token
  cvvrf: MGMT
  disable_aaa: true
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
enable_password:
  disabled: true
errdisable:
  recovery:
    interval: 30
ethernet_interfaces:
- name: Ethernet2
  description: P2P_ARI-SP-401-SKY_Ethernet4
  shutdown: false
  speed: forced 100g
  mtu: 9214
  link_tracking_groups:
  - name: LT_GROUP1
    direction: upstream
  ip_address: 10.111.8.25/31
  service_profile: santander_trust_dscp
  peer: ARI-SP-401-SKY
  peer_interface: Ethernet4
  peer_type: spine
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet3
  description: P2P_ARI-SP-402-SKY_Ethernet4
  shutdown: false
  speed: forced 100g
  mtu: 9214
  link_tracking_groups:
  - name: LT_GROUP1
    direction: upstream
  ip_address: 10.111.8.27/31
  service_profile: santander_trust_dscp
  peer: ARI-SP-402-SKY
  peer_interface: Ethernet4
  peer_type: spine
  sflow:
    enable: true
  switchport:
    enabled: false
- name: Ethernet4
  description: SERVER_oh1xar2esxc0201_Ethernet1
  shutdown: false
  speed: 25g
  link_tracking_groups:
  - name: LT_GROUP1
    direction: downstream
  spanning_tree_portfast: edge
  peer: oh1xar2esxc0201
  peer_interface: Ethernet1
  peer_type: server
  port_profile: TRUNK_25G_Compute_NG_PRODUCCION
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 150,177
hostname: ARI-CL-403-SKY
interface_defaults:
  ethernet:
    shutdown: true
  mtu: 9100
ip_icmp_redirect: false
ip_igmp_snooping:
  globally_enabled: false
ip_routing: true
ip_tacacs_source_interfaces:
- name: Management0
  vrf: MGMT
ip_virtual_router_mac_address: 00:1c:73:ca:fe:66
lacp:
  port_id:
    range:
      begin: 129
      end: 256
link_tracking_groups:
- name: LT_GROUP1
  recovery_delay: 300
load_interval:
  default: 5
local_users:
- name: admin
  privilege: 15
  role: network-admin
  sha512_password: $6$U3al1DzxMmPfRugU$tkAtrfWNjAKPDS0GNes73ZIChBYBRkVz9juKlLMbE3rYmPnfGoXBJClFPeo92p7Z3L29.FwW11JD82mTyCMaf/
- name: ansible
  privilege: 15
  role: network-admin
  sha512_password: $6$BLP4ybyxd.MVHa.3$9LRJR4bFFH1aQSXThMevlMPl1APzz8Rszk9VADYlZJSYl0M5Lznbyec4KBDDyaIVNZ7o0V60bVwx1zXmSzybS1
- name: arista
  privilege: 15
  role: network-admin
  sha512_password: $6$YTqtFEXPeyY/KTfe$3ssGibfbON87.C4Zr7pbZ4.uy8BJDLJUzniLGzTac333KOHbYlgziMldZDKqk55SFQ4DL.SyHK5or5RUFdDVu0
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$PyJWbjPrhxpt9MvC$kLSV2naOFChW09CqBcZfVSOBpv.3v0NM7NAbGoQINfoTJlLb/LfoToRkCcGMeSDENrUa193Ba/NeB2pS3J9XP1
- name: marcelo
  privilege: 15
  role: network-admin
  sha512_password: $6$JOlaFRui.uKQAgcY$F.A6VZCIcIlbRMrk//U2.q9ucyl95ymC1dGz9BLpwl3NkIhLbOkCh.N.nYaiLBIUdz3mXzAAutF/APAAtamUB.
logging:
  console: notifications
  monitor: debugging
  buffered:
    size: 8000
    level: notifications
  trap: debugging
  format:
    timestamp: high-resolution
  source_interface: Management0
  vrfs:
  - name: MGMT
    source_interface: Management0
    hosts:
    - name: 10.200.251.15
      protocol: udp
    - name: 10.206.16.75
      protocol: udp
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 10.111.5.7/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 10.111.6.7/32
- name: Loopback1001
  description: DIAG_VRF_VRF-NEXTGEN_PRODUCCION
  shutdown: false
  vrf: VRF-NEXTGEN_PRODUCCION
  ip_address: 10.111.7.7/32
mac_address_table:
  aging_time: 1800
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
    access_group: CVP-ACL
management_console:
  idle_timeout: 15
management_interfaces:
- name: Management0
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.124/24
  type: oob
  gateway: 192.168.0.1
management_security:
  password:
    encryption_key_common: true
management_ssh:
  idle_timeout: 15
  enable: true
  vrfs:
  - name: MGMT
    enable: true
    ip_access_group_in: MGMT-ACL
  - name: default
    enable: false
  - name: VRF-NEXTGEN_PRODUCCION
    enable: false
  - name: VRF-NEXTGEN_DESARROLLO
    enable: false
  - name: VRF-NEXTGEN_DMZ_INT
    enable: false
  - name: VRF-NEXTGEN_DMZ_FRONT
    enable: false
  - name: VRF-NEXTGEN_MGMT
    enable: false
  - name: VRF-NEXTGEN_MGMT_DMZ
    enable: false
metadata:
  is_deployed: true
  platform: 7050X3
  dc_name: NEXTGEN_ARGENTINA_PRO_DC2
  fabric_name: NEXTGEN_ARGENTINA_PRO
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.111.5.0/24 eq 32
  - sequence: 20
    action: permit 10.111.6.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65104'
  router_id: 10.111.5.7
  maximum_paths:
    paths: 128
    ecmp: 128
  updates:
    wait_install: true
  bgp_defaults:
  - update wait-install
  - no bgp default ipv4-unicast
  - bgp asn notation asplain
  - distance bgp 20 200 200
  - timers bgp 5 15
  - neighbor default send-community
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    password: $1c$caHDPKDBzOjl6ZrDQLicDQ==
    send_community: all
    maximum_routes: 12000
  - name: EVPN-OVERLAY-PEERS
    type: evpn
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    password: $1c$caHDPKDBzOjl6ZrDQLicDQ==
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 10.111.8.24
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: ARI-SP-401-SKY
    description: ARI-SP-401-SKY_Ethernet4
  - ip_address: 10.111.8.26
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    peer: ARI-SP-402-SKY
    description: ARI-SP-402-SKY_Ethernet4
  - ip_address: 10.111.5.1
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65101'
    peer: ARI-SP-401-SKY
    description: ARI-SP-401-SKY_Loopback0
  - ip_address: 10.111.5.2
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65101'
    peer: ARI-SP-402-SKY
    description: ARI-SP-402-SKY_Loopback0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlans:
  - id: 150
    tenant: T_NEXTGEN_PRODUCCION
    rd: 10.111.5.7:10150
    route_targets:
      both:
      - 10150:10150
    redistribute_routes:
    - learned
  - id: 177
    tenant: T_NEXTGEN_PRODUCCION
    rd: 10.111.5.7:10177
    route_targets:
      both:
      - 10177:10177
    redistribute_routes:
    - learned
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
    route:
      import_match_failure_action: discard
  address_family_rtc:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
    - name: EVPN-OVERLAY-PEERS
      activate: false
  vrfs:
  - name: VRF-NEXTGEN_PRODUCCION
    rd: 10.111.5.7:1001
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 1001:1001
      export:
      - address_family: evpn
        route_targets:
        - 1001:1001
    router_id: 10.111.5.7
    redistribute:
      connected:
        enabled: true
service_routing_protocols_model: multi-agent
sflow:
  sample: 131072
  destinations:
  - destination: 127.0.0.1
  source_interface: Loopback0
  interface:
    disable:
      default: true
  run: true
snmp_server:
  local_interfaces:
  - name: Management0
    vrf: MGMT
  groups:
  - name: ROGROUP
    version: v3
    authentication: priv
  users:
  - name: itmetro
    group: ROGROUP
    version: v3
    auth: sha
    auth_passphrase: N3CVXEq3q2mE8buU
    priv: aes
    priv_passphrase: 6WJp9NFNyLKeMj6n
  hosts:
  - host: 10.40.3.124
    vrf: MGMT
    version: '3'
    users:
    - username: itmetro
      authentication_level: priv
  - host: 10.40.3.125
    vrf: MGMT
    version: '3'
    users:
    - username: itmetro
      authentication_level: priv
  - host: 10.40.3.126
    vrf: MGMT
    version: '3'
    users:
    - username: itmetro
      authentication_level: priv
  - host: 10.40.3.127
    vrf: MGMT
    version: '3'
    users:
    - username: itmetro
      authentication_level: priv
  traps:
    enable: true
    snmp_traps:
    - name: bridge arista-mac-age
      enabled: false
    - name: bridge arista-mac-learn
      enabled: false
    - name: bridge arista-mac-move
      enabled: false
    - name: entity arista-ent-sensor-alarm
      enabled: false
  vrfs:
  - name: MGMT
    enable: true
spanning_tree:
  root_super: true
  edge_port:
    bpduguard_default: true
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 32768
standard_access_lists:
- name: CVP-ACL
  sequence_numbers:
  - sequence: 10
    action: permit 0.0.0.0/0
- name: MGMT-ACL
  sequence_numbers:
  - sequence: 10
    action: permit 0.0.0.0/0
static_routes:
- vrf: MGMT
  prefix: 0.0.0.0/0
  next_hop: 192.168.0.1
switchport_default:
  mode: routed
tacacs_servers:
  hosts:
  - host: 180.250.33.126
    vrf: MGMT
    key: 00373625367E3F575D72181B
  - host: 180.250.33.127
    vrf: MGMT
    key: 00373625367E3F575D72181B
  policy_unknown_mandatory_attribute_ignore: false
terminal:
  length: 60
transceiver_qsfp_default_mode_4x10: true
virtual_source_nat_vrfs:
- name: VRF-NEXTGEN_PRODUCCION
  ip_address: 10.111.7.7
vlan_interfaces:
- name: Vlan150
  description: NEXTGEN_PRODUCCION_Vl_150
  shutdown: true
  vrf: VRF-NEXTGEN_PRODUCCION
  ip_address_virtual: 10.40.0.1/20
  tenant: T_NEXTGEN_PRODUCCION
  tags:
  - PRODUCCION
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 3800
    ending: 4000
vlans:
- id: 150
  name: NEXTGEN_PRODUCCION_Vl_150
  tenant: T_NEXTGEN_PRODUCCION
- id: 177
  name: NEXTGEN_PRODUCCION_Vl_177
  tenant: T_NEXTGEN_PRODUCCION
vrfs:
- name: MGMT
  ip_routing: false
- name: VRF-NEXTGEN_PRODUCCION
  ip_routing: true
  tenant: T_NEXTGEN_PRODUCCION
vxlan_interface:
  vxlan1:
    description: ARI-CL-403-SKY_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vlans:
      - id: 150
        vni: 10150
      - id: 177
        vni: 10177
      vrfs:
      - name: VRF-NEXTGEN_PRODUCCION
        vni: 1001
