---
#See available tests at https://anta.arista.com/stable/api/tests/

anta.tests.system:
  # Verifies the device uptime is higher than a value.
  - VerifyUptime:
      minimum: 10
  - VerifyReloadCause:
  - VerifyCoredump:
  - VerifyAgentLogs:
  - VerifyCPUUtilization:
  # Added new test
  - VerifyFileSystemUtilization:
  - VerifyNTP:

anta.tests.hardware:
  - VerifyEnvironmentCooling:
      states:
        - ok
  - VerifyEnvironmentPower:
      states:
        - ok
  - VerifyEnvironmentSystemCooling:
  - VerifyTemperature:
  - VerifyTransceiversManufacturers:
      manufacturers:
        - Not Present
        - Arista Networks
        - Arastra, Inc.
        - Dell
        - DELL EMC

anta.tests.lanz:
  - VerifyLANZ:

anta.tests.software:
  - VerifyEOSVersion:
      # List of allowed EOS versions.
      versions:
        - 4.32.6.1M
  - VerifyTerminAttrVersion:
      versions:
        - v1.34.6
  
#Load anta.tests.configuration
anta.tests.configuration:
  # Verifies ZeroTouch is disabled.
  - VerifyZeroTouch:
  - VerifyRunningConfigDiffs:

#Load anta.tests.bfd
anta.tests.bfd:
  - VerifyBFDPeersHealth:
      down_threshold: 2

#Load anta.tests.stp
anta.tests.stp:
  - VerifySTPMode:
  #STP mode to verify. Supported values: mstp, rstp, rapidPvst. Defaults to mstp.
        vlans:
        - 150
        - 151
  - VerifySTPRootPriority:
      priority: 0
  - VerifySTPBlockedPorts:

#Load anta.tests.interfaces
anta.tests.interfaces:
  - VerifyPortChannels:
  - VerifyInterfaceDiscards:
  - VerifyInterfaceErrDisabled:
  - VerifyInterfaceErrors:
  - VerifyInterfaceUtilization:
      threshold: 50.0

#Load anta.tests.mlag
anta.tests.mlag:
  - VerifyMlagConfigSanity:
  - VerifyMlagInterfaces:
  - VerifyMlagStatus:

#Load anta.tests.connectivity
anta.tests.connectivity:
  - VerifyReachability:
      hosts:
        - source: Management1
          destination: 10.0.60.7
          vrf: MGMT
        - source: Management1
          destination: 10.0.60.8
          vrf: MGMT
        - source: Loopback0
          destination: 10.110.6.10
          vrf: default
        - source: Loopback0
          destination: 10.110.6.11
          vrf: default
      filters:
        # tags: ['leaf', 'spine']
      result_overwrite:
        categories:
          - "Overwritten category 1"
        description: "Test with overwritten description"
        custom_field: "Test run by Marcelo Carvalho"

#Load anta.tests.services
#anta.tests.services:
#  - VerifyDNSLookup:
#      domain_names:
#        - arista.com
#        - google.com

#Load anta.tests.security
anta.tests.security:
  - VerifyTelnetStatus:
  - VerifySSHStatus:

anta.tests.vxlan:
  - VerifyVxlan1Interface:
      result_overwrite:
        "custom_field": "Generated by Marcelo"
  - VerifyVxlan1ConnSettings:
      source_interface: Loopback1
      udp_port: 4789
      result_overwrite:
        "custom_field": "Generated by Marcelo"
  - VerifyVxlanConfigSanity:
      result_overwrite:
        "custom_field": "Generated by Marcelo"

# anta.tests.routing:
#   ospf:
#     - VerifyOSPFNeighborState:
#         result_overwrite:
#           "custom_field": "Generated by JA"
#     - VerifyOSPFMaxLSA:
#         result_overwrite:
#           "custom_field": "Generated by JA"

anta.tests.evpn:
  - VerifyEVPNType5Routes:
      result_overwrite:
        "custom_field": "Generated by Marcelo"
      filters:
        # tags: [ leaf ]
      prefixes:
        # At least one active/valid path across all RDs
        - address: 0.0.0.0/0
          vni: 1005
        - address: 10.114.0.0/23
          vni: 1005
