---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: NEXTGEN_ARGENTINA_PRO
dc_name: NEXTGEN_ARGENTINA_PRO_DC2
# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1

## Parameters for Validate State
ansible_user: marcelo
ansible_password: marcelo
ansible_network_os: eos
ansible_become: true
ansible_connection: httpapi

# Accept other Manufactures for Transceivers
accepted_xcvr_manufacturers:
  - Not Present
  - DELL EMC
  - Dell
  - Arista Networks
  - Arastra, Inc.

# Enable vlan aware bundles
evpn_vlan_aware_bundles: false

# Disable igmp snooping default
default_igmp_snooping_enabled: false

# Enable VPN import pruning (Min. EOS 4.24.2F)
# The Route Target extended communities carried by incoming VPN paths will
# be examined. If none of those Route Targets have been configured for import,
# the path will be immediately discarded
evpn_import_pruning: true

# Enable RT membership
evpn_overlay_bgp_rtc: true

bgp_maximum_paths: 128
bgp_ecmp: 128


# bgp peer groups passwords
bgp_peer_groups:
  ipv4_underlay_peers:
    password: "{{ bgp_pg.az2.underlay }}"
  evpn_overlay_peers:
    password: "{{ bgp_pg.az2.overlay }}"

# Spine Switches
spine:
  defaults:
    platform: 7260CX3
    bgp_as: 65101
    loopback_ipv4_pool: 10.111.5.0/24
    structured_config:
      router_bgp:
        peer_groups:
          - name: EVPN-OVERLAY-SPINES
            type: evpn
            remote_as: 65041
            description: "EVPN to DC1 RR"
            next_hop_unchanged: true
            update_source: loopback0
            ebgp_multihop: 3
            bfd: true
            send_community: all
          - name: IPv4-UNDERLAY-PEERS
            bfd: false
          - name: EVPN-OVERLAY-PEERS
        neighbors:
          - ip_address: 10.110.5.1
            peer_group: EVPN-OVERLAY-SPINES
          - ip_address: 10.110.5.2
            peer_group: EVPN-OVERLAY-SPINES
        address_family_evpn:
          peer_groups:
            - name: EVPN-OVERLAY-SPINES
              activate: true
    bgp_defaults:
      - update wait-for-convergence
      - update wait-install
      - bgp asn notation asplain
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      - timers bgp 5 15
      - graceful-restart
      - graceful-restart restart-time 300
      - neighbor default send-community
  nodes:
    - name: ARI-SP-401-SKY
      id: 1
      mgmt_ip: 192.168.0.20/24
    - name: ARI-SP-402-SKY
      id: 2
      mgmt_ip: 192.168.0.21/24

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    platform: 7050X3
    bgp_as: 65102-65150
    # virtual router mac for VNIs assigned to Leaf switches
    virtual_router_mac_address: 00:1c:73:ca:fe:66
    uplink_ipv4_pool: 10.111.8.0/23
    loopback_ipv4_pool: 10.111.5.0/24
    vtep_loopback_ipv4_pool: 10.111.6.0/24
    loopback_ipv4_offset: 4
    max_uplink_switches: 6
    mlag: false
    uplink_interfaces: [Ethernet2, Ethernet3]
    uplink_switches:
      - ARI-SP-401-SKY
      - ARI-SP-402-SKY
    uplink_interface_speed: forced 100g
    # spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    spanning_tree_root_super: true
    bgp_defaults:
      - update wait-install
      - no bgp default ipv4-unicast
      - bgp asn notation asplain
      - distance bgp 20 200 200
      - timers bgp 5 15
      - neighbor default send-community

  node_groups:
    - group: NEXTGEN_ARGENTINA_PRO_DC2_CL401_402
      filter:
        tags:
          - ALL-FABRIC
          - PRODUCCION
          - MGMT_PROD
      link_tracking:
        enabled: true
        groups:
          - name: LT_GROUP1
            recovery_delay: 300
      lacp_port_id_range:
        enabled: true
        offset: 128
      structured_config:
        spanning_tree:
          edge_port:
            bpduguard_default: true
      nodes:
        - name: ARI-CL-401-SKY
          id: 1
          mgmt_ip: 192.168.0.122/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
        - name: ARI-CL-402-SKY
          id: 2
          mgmt_ip: 192.168.0.123/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]

    - group: NEXTGEN_ARGENTINA_PRO_DC2_CL403_404
      filter:
        tags:
          - ALL-FABRIC
          - PRODUCCION
          - MGMT_PROD
      link_tracking:
        enabled: true
        groups:
          - name: LT_GROUP1
            recovery_delay: 300
      lacp_port_id_range:
        enabled: true
        offset: 128
      structured_config:
        spanning_tree:
          edge_port:
            bpduguard_default: true
      nodes:
        - name: ARI-CL-403-SKY
          id: 3
          mgmt_ip: 192.168.0.124/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
        - name: ARI-CL-404-SKY
          id: 4
          mgmt_ip: 192.168.0.125/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5]

    - group: NEXTGEN_ARGENTINA_PRO_DC2_BL401_402
      uplink_switches:
        - ARI-SP-401-SKY
        - ARI-SP-402-SKY
      spanning_tree_mode: none
      spanning_tree_root_super: false
      link_tracking:
        enabled: true
        groups:
          - name: LT_GROUP1
            recovery_delay: 300
      lacp_port_id_range:
        enabled: true
        offset: 128
      nodes:
        - name: ARI-BL-401-SKY
          filter:
            always_include_vrfs_in_tenants:
              - 'T_INFRA_MGMT_MGMT'
            tags:
              - ALL-FABRIC
              - PRODUCCION
              - DESARROLLO
              - MGMT
              - MGMT_DMZ
              - MGMT_PROD
              - DMZ_INT
              - DMZ_FRONT
              - PRODUCCION-BL401-SKY
          #
          # id 21-30 reserved for border leafs
          id: 21
          mgmt_ip: 192.168.0.200/24
          uplink_switch_interfaces: [Ethernet7, Ethernet7]
          uplink_interfaces: [Ethernet2, Ethernet3]

        - name: ARI-BL-402-SKY
          filter:
            always_include_vrfs_in_tenants:
              - 'T_INFRA_MGMT_MGMT'
            tags:
              - ALL-FABRIC
              - PRODUCCION
              - DESARROLLO
              - MGMT
              - MGMT_DMZ
              - MGMT_PROD
              - DMZ_INT
              - DMZ_FRONT
              - PRODUCCION-BL402-SKY
          #
          # id 21-30 reserved for border leafs
          id: 22
          mgmt_ip: 192.168.0.201/24
          uplink_switch_interfaces: [Ethernet8, Ethernet8]
          uplink_interfaces: [Ethernet2, Ethernet3]

p2p_uplinks_mtu: 9214
p2p_uplinks_qos_profile: santander_trust_dscp

# Adjust default bfd values
bfd_multihop:
  interval: 300
  min_rx: 300
  multiplier: 3
