---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: NEXTGEN_ARGENTINA_PRO
dc_name: NEXTGEN_ARGENTINA_PRO_DC1
# OOB Management network default gateway.
mgmt_gateway: 10.0.60.1

## Parameters for Validate State
ansible_user: marcelo
ansible_password: marcelo
ansible_network_os: eos
ansible_become: true
ansible_connection: httpapi

# Accept other Manufactures for Transceivers
accepted_xcvr_manufacturers:
  - Not Present
  - DELL EMC
  - Dell
  - Arista Networks
  - Arastra, Inc.

# Enable vlan aware bundles
evpn_vlan_aware_bundles: false

# Disable igmp snooping default
default_igmp_snooping_enabled: false

# Enable VPN import pruning (Min. EOS 4.24.2F)
# The Route Target extended communities carried by incoming VPN paths will
# be examined. If none of those Route Targets have been configured for import,
# the path will be immediately discarded
evpn_import_pruning: true

# Enable RT membership
evpn_overlay_bgp_rtc: true

bgp_maximum_paths: 128
bgp_ecmp: 128


# bgp peer groups passwords
bgp_peer_groups:
  ipv4_underlay_peers:
    password: "{{ bgp_pg.az1.underlay }}"
  evpn_overlay_peers:
    password: "{{ bgp_pg.az1.overlay }}"

# Spine Switches
spine:
  defaults:
    platform: 7260CX3
    bgp_as: 65041
    loopback_ipv4_pool: 10.110.5.0/24
    structured_config:
      router_bgp:
        peer_groups:
          - name: EVPN-OVERLAY-SPINES
            type: evpn
            remote_as: 65101
            description: "EVPN to DC2 RR"
            next_hop_unchanged: true
            update_source: loopback0
            ebgp_multihop: 3
            bfd: true
            send_community: all
          - name: IPv4-UNDERLAY-PEERS
            bfd: false
          - name: EVPN-OVERLAY-PEERS
        neighbors:
          - ip_address: 10.111.5.1
            peer_group: EVPN-OVERLAY-SPINES
          - ip_address: 10.111.5.2
            peer_group: EVPN-OVERLAY-SPINES
        address_family_evpn:
          peer_groups:
            - name: EVPN-OVERLAY-SPINES
              activate: true
    bgp_defaults:
      - update wait-for-convergence
      - update wait-install
      - bgp asn notation asplain
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      - timers bgp 5 15
      - graceful-restart
      - graceful-restart restart-time 300
      - neighbor default send-community
  nodes:
    - name: ARI-SP-301-MTZ
      id: 1
      mgmt_ip: 10.0.60.31/23
    - name: ARI-SP-302-MTZ
      id: 2
      mgmt_ip: 10.0.60.32/23

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    platform: 7050X3
    bgp_as: 65042-65090
    # virtual router mac for VNIs assigned to Leaf switches
    virtual_router_mac_address: 00:1c:73:ca:fe:66
    uplink_ipv4_pool: 10.110.8.0/23
    loopback_ipv4_pool: 10.110.5.0/24
    vtep_loopback_ipv4_pool: 10.110.6.0/24
    loopback_ipv4_offset: 4
    max_uplink_switches: 6
    mlag: false
    uplink_interfaces: [Ethernet49/1, Ethernet50/1]
    uplink_switches:
      - ARI-SP-301-MTZ
      - ARI-SP-302-MTZ
    uplink_interface_speed: forced 100g
    # spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    spanning_tree_root_super: true
    bgp_defaults:
      - update wait-install
      - no bgp default ipv4-unicast
      - bgp asn notation asplain
      - distance bgp 20 200 200
      - timers bgp 5 15
      - neighbor default send-community

  node_groups:
    - group: NEXTGEN_ARGENTINA_PRO_DC1_CL301_302
      filter:
        tags:
          - ALL-FABRIC
          - PRODUCCION
          - MGMT_PROD
      link_tracking:
        enabled: true
        groups:
          - name: LT_GROUP1
            recovery_delay: 300
      lacp_port_id_range:
        enabled: true
        offset: 128
      structured_config:
        spanning_tree:
          edge_port:
            bpduguard_default: true
      nodes:
        - name: ARI-CL-301-MTZ
          id: 1
          mgmt_ip: 10.0.60.35/23
          uplink_switch_interfaces: [Ethernet1/1, Ethernet1/1]
        - name: ARI-CL-302-MTZ
          id: 2
          mgmt_ip: 10.0.60.36/23
          uplink_switch_interfaces: [Ethernet2/1, Ethernet2/1]

    - group: NEXTGEN_ARGENTINA_PRO_DC1_CL303_304
      filter:
        tags:
          - ALL-FABRIC
          - PRODUCCION
          - MGMT_PROD
      link_tracking:
        enabled: true
        groups:
          - name: LT_GROUP1
            recovery_delay: 300
      lacp_port_id_range:
        enabled: true
        offset: 128
      structured_config:
        spanning_tree:
          edge_port:
            bpduguard_default: true
      nodes:
        - name: ARI-CL-303-MTZ
          id: 3
          mgmt_ip: 10.0.60.37/23
          uplink_switch_interfaces: [Ethernet3/1, Ethernet3/1]
        - name: ARI-CL-304-MTZ
          id: 4
          mgmt_ip: 10.0.60.38/23
          uplink_switch_interfaces: [Ethernet4/1, Ethernet4/1]

    - group: NEXTGEN_ARGENTINA_PRO_DC1_CL305_306
      filter:
        tags:
          - ALL-FABRIC
          - PRODUCCION
          - MGMT_PROD
      link_tracking:
        enabled: true
        groups:
          - name: LT_GROUP1
            recovery_delay: 300
      lacp_port_id_range:
        enabled: true
        offset: 128
      structured_config:
        spanning_tree:
          edge_port:
            bpduguard_default: true
      nodes:
        - name: ARI-CL-305-MTZ
          id: 5
          mgmt_ip: 10.0.60.39/23
          uplink_switch_interfaces: [Ethernet5/1, Ethernet5/1]
        - name: ARI-CL-306-MTZ
          id: 6
          mgmt_ip: 10.0.60.40/23
          uplink_switch_interfaces: [Ethernet6/1, Ethernet6/1]

    - group: NEXTGEN_ARGENTINA_PRO_DC1_CL307_308
      filter:
        tags:
          - ALL-FABRIC
          - PRODUCCION
          - MGMT_PROD
      link_tracking:
        enabled: true
        groups:
          - name: LT_GROUP1
            recovery_delay: 300
      lacp_port_id_range:
        enabled: true
        offset: 128
      structured_config:
        spanning_tree:
          edge_port:
            bpduguard_default: true
      nodes:
        - name: ARI-CL-307-MTZ
          id: 7
          mgmt_ip: 10.0.60.41/23
          uplink_switch_interfaces: [Ethernet7/1, Ethernet7/1]
        - name: ARI-CL-308-MTZ
          id: 8
          mgmt_ip: 10.0.60.42/23
          uplink_switch_interfaces: [Ethernet8/1, Ethernet8/1]

    - group: NEXTGEN_ARGENTINA_PRO_DC1_CL309_310
      filter:
        tags:
          - ALL-FABRIC
          - MGMT
          - MGMT_DMZ
          - DMZ_INT
          - DMZ_FRONT
      link_tracking:
        enabled: true
        groups:
          - name: LT_GROUP1
            recovery_delay: 300
      lacp_port_id_range:
        enabled: true
        offset: 128
      structured_config:
        spanning_tree:
          edge_port:
            bpduguard_default: true
      nodes:
        - name: ARI-CL-309-MTZ
          id: 9
          mgmt_ip: 10.0.60.43/23
          uplink_switch_interfaces: [Ethernet9/1, Ethernet9/1]
        - name: ARI-CL-310-MTZ
          id: 10
          mgmt_ip: 10.0.60.44/23
          uplink_switch_interfaces: [Ethernet10/1, Ethernet10/1]

    - group: NEXTGEN_ARGENTINA_PRO_DC1_BL301_302
      uplink_switches:
        - ARI-SP-301-MTZ
        - ARI-SP-302-MTZ
      spanning_tree_mode: none
      spanning_tree_root_super: false
      link_tracking:
        enabled: true
        groups:
          - name: LT_GROUP1
            recovery_delay: 300
      lacp_port_id_range:
        enabled: true
        offset: 128
      nodes:
        - name: ARI-BL-301-MTZ
          filter:
            always_include_vrfs_in_tenants:
              - 'T_INFRA_MGMT_MGMT'
            tags:
              - ALL-FABRIC
              - PRODUCCION
              - DESARROLLO
              - MGMT
              - MGMT_DMZ
              - MGMT_PROD
              - DMZ_INT
              - DMZ_FRONT
              - PRODUCCION-BL301-MTZ
          #
          # id 21-30 reserved for border leafs
          id: 21
          mgmt_ip: 10.0.60.33/23
          uplink_switch_interfaces: [Ethernet11/1, Ethernet11/1]
          uplink_interfaces: [Ethernet31/1, Ethernet32/1]

        - name: ARI-BL-302-MTZ
          filter:
            always_include_vrfs_in_tenants:
              - 'T_INFRA_MGMT_MGMT'
            tags:
              - ALL-FABRIC
              - PRODUCCION
              - DESARROLLO
              - MGMT
              - MGMT_DMZ
              - MGMT_PROD
              - DMZ_INT
              - DMZ_FRONT
              - PRODUCCION-BL302-MTZ
          #
          # id 21-30 reserved for border leafs
          id: 22
          mgmt_ip: 10.0.60.34/23
          uplink_switch_interfaces: [Ethernet12/1, Ethernet12/1]
          uplink_interfaces: [Ethernet31/1, Ethernet32/1]

p2p_uplinks_mtu: 9214
p2p_uplinks_qos_profile: santander_trust_dscp

# Adjust default bfd values
bfd_multihop:
  interval: 300
  min_rx: 300
  multiplier: 3
